### PR TITLE
fixed base issue

### PR DESCRIPTION
**Pull request by bizarf**
I modified the build command in package.json back to the original vite one, and changed the base in vite.config as well. The base parameter should always be the repositories name.

### CODE REVIEW

**Comment by pethoburr** [comment]
Hey thank you so much for trying to help I merged that pull request and it
redeployed the site but im still getting 404 error failed to load resource

**Comment by bizarf** [comment]
Try to run `npm run deploy` from your side. the gh-pages tree still has the files from before the merge. 
https://github.com/pethoburr/devPortfolio/tree/gh-pages

**Comment by pethoburr** [comment]
Hello I tried that as well and pushed the changes and am still getting the
same 404 error failed to load resource

**Comment by pethoburr** [comment]
its now showing this error in the console: GET
https://pethoburr.github.io/src/main.jsx net::ERR_ABORTED 404

**Comment by pethoburr** [comment]
Hello sorry to bother you again but now im getting this error: Failed to
load module script: Expected a JavaScript module script but the server
responded with a MIME type of "text/jsx". Strict MIME type checking is
enforced for module scripts per HTML spec.

**Comment by pethoburr** [comment]
Hey I figured it out I was using Jekyll Github Actions when instead I
should have used custom and copy and pasted the vite docs yml file. I had
tried copy and pasting that into the jekyll deploy file but it didnt work
and went back to the one that was auto built. Thank you so much for your
help!

**Comment by bizarf** [comment]
Oh, I've never used Github Actions so I had no idea that could cause problems. Congrats on fixing the issue!

**Pull request merged**
